# Generated by Django 5.0.2 on 2024-03-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_latitude_alter_customuser_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок новости.', max_length=255, verbose_name='Заголовок')),
                ('info', models.TextField(help_text='Описание новости.', verbose_name='Описание')),
                ('url', models.URLField(help_text='URL новости.', verbose_name='URL')),
                ('time', models.CharField(help_text='Время новости.', max_length=255, verbose_name='Время')),
                ('date', models.DateField(auto_now_add=True, help_text='Дата новости.', verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания новости.', verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
