# Generated by Django 5.0.2 on 2024-03-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='popular',
            field=models.BooleanField(default=False, help_text='Указывает, является ли новость популярной.', verbose_name='Популярная'),
        ),
    ]
