# Generated by Django 5.0.2 on 2024-03-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_news_popular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='popular',
            field=models.BooleanField(default=True, help_text='Указывает, является ли новость популярной.', verbose_name='Популярная'),
        ),
    ]
